### ISSUE TITLE
Joomla 3.8 - Unable to create Logger instance

### ISSUE THREAD

**Issue by PeterTHM** [chdemko/joomla-external-login#47]
Hi! It seems that there is an issue with the logging since Joomla 3.8 moved the Logger to the libraries/src folder and added namespace usage for it.

![image](https://user-images.githubusercontent.com/6030715/31278621-f5bc09d8-aaa5-11e7-8b11-5e0ddbf65ac5.png)

We currently avoid this behaviour on Joomla 3.8 by deactivating the logging.

Regards
Peter

**Comment by manubelin** [comment]
Bonjour,
j'ai le même problème avec joomla 3.8.1, une idée ?
merci pour le développement

**Comment by gregkoron** [comment]
Hi, does anyone know what files are affected so as to make the necessary changes?
Thank you in advance!

**Comment by gregkoron** [comment]
Finally, I managed to fix it. 

1) In order to keep the logs, you have to create the "libraries\joomla\log\" and paste the content of "log" folder which can be taken from an older version than J 3.8. I do not know, at this point, if this change will cause any troubles, however I have not noticed any problem till now.

2) In order to get rid of the ticket that is appended to the URL like "?ticket=ST-876975-bV2QbNrafrdw0ZxeDhIp-sso.___.com", you have to disable the "System - Page Cache" plugin. If you still have some problems, play with the parameters of the params column of Table "__externallogin_server".

**Comment by chdemko** [comment]
Currently, I have not the time to fix it. You can propose a pull request if you want.
